version: "3.8"
services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /usr/src/app
    volumes:
      - ./journal_api:/usr/src/app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=pg
      - DB_PORT=5432
      - DEBUG=1
      - SECRET_KEY=dev-secret-please-change
    ports:
      - "8000:8000"
    depends_on:
      - pg

  pg:
    image: postgres:16-alpine
    container_name: tj_pg
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: tj_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg

volumes:
  pg_data:
